apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "local-mysql.fullname" . }}-initdb
data:
  01-init-databases.sql: |
{{- range .Values.databases }}
    CREATE DATABASE IF NOT EXISTS `{{ . }}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
{{- end }}
