CREATE TABLE IF NOT EXISTS order_groups (
    id BIGINT NOT NULL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    source VARCHAR(16) NOT NULL,
    total_item_amount BIGINT NOT NULL,
    total_shipping_amount BIGINT NOT NULL,
    total_pay_amount BIGINT NOT NULL,
    currency VARCHAR(8) NOT NULL,
    shop_order_count INT NOT NULL,
    item_count INT NOT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    KEY idx_order_groups_user_created (user_id, created_at),
    KEY idx_order_groups_user_status_created (user_id, status, created_at)
);

CREATE TABLE IF NOT EXISTS order_group_addresses (
    id BIGINT NOT NULL PRIMARY KEY,
    order_group_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    receiver_name VARCHAR(64) NOT NULL,
    receiver_phone VARCHAR(32) NOT NULL,
    country_code VARCHAR(16) NOT NULL,
    province VARCHAR(64) NOT NULL,
    city VARCHAR(64) NOT NULL,
    district VARCHAR(64) NOT NULL,
    address_line1 VARCHAR(255) NOT NULL,
    address_line2 VARCHAR(255) NULL,
    postal_code VARCHAR(32) NULL,
    tag VARCHAR(32) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    UNIQUE KEY uk_order_group_addresses_group_id (order_group_id),
    CONSTRAINT fk_order_group_addresses_group_id FOREIGN KEY (order_group_id) REFERENCES order_groups (id)
);

CREATE TABLE IF NOT EXISTS shop_orders (
    id BIGINT NOT NULL PRIMARY KEY,
    order_group_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    shop_id BIGINT NOT NULL,
    shop_name VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL,
    item_amount BIGINT NOT NULL,
    shipping_amount BIGINT NOT NULL,
    pay_amount BIGINT NOT NULL,
    currency VARCHAR(8) NOT NULL,
    item_count INT NOT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    KEY idx_shop_orders_group_id (order_group_id),
    KEY idx_shop_orders_user_created (user_id, created_at),
    KEY idx_shop_orders_shop_status_created (shop_id, status, created_at),
    CONSTRAINT fk_shop_orders_group_id FOREIGN KEY (order_group_id) REFERENCES order_groups (id)
);

CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT NOT NULL PRIMARY KEY,
    order_group_id BIGINT NOT NULL,
    shop_order_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    shop_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    sku_id BIGINT NOT NULL,
    product_title VARCHAR(255) NOT NULL,
    product_sub_title VARCHAR(255) NOT NULL,
    main_image_url VARCHAR(512) NOT NULL,
    sku_name VARCHAR(255) NOT NULL,
    price_amount BIGINT NOT NULL,
    currency VARCHAR(8) NOT NULL,
    quantity INT NOT NULL,
    item_amount BIGINT NOT NULL,
    review_status_snapshot VARCHAR(32) NOT NULL,
    product_sale_status_snapshot VARCHAR(32) NOT NULL,
    sku_sale_status_snapshot VARCHAR(32) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    KEY idx_order_items_group_id (order_group_id),
    KEY idx_order_items_shop_order_id (shop_order_id),
    KEY idx_order_items_user_created (user_id, created_at),
    CONSTRAINT fk_order_items_group_id FOREIGN KEY (order_group_id) REFERENCES order_groups (id),
    CONSTRAINT fk_order_items_shop_order_id FOREIGN KEY (shop_order_id) REFERENCES shop_orders (id)
);
